# Development override file for docker-compose.yml
# This file is automatically loaded by docker-compose and can be customized per developer
# Copy this file to docker-compose.override.yml and modify as needed

version: '3.8'

services:
  # Override app service for development
  app:
    build:
      dockerfile: Dockerfile.dev
    environment:
      # Override with development-specific environment variables
      NODE_ENV: development
      LOG_LEVEL: 3 # More verbose logging in development

      # Development database settings
      DB_MAX_POOL_SIZE: 5
      DB_MIN_POOL_SIZE: 1

      # Development Redis settings
      REDIS_HOST: host.docker.internal
      REDIS_PASSWORD: # No password for local development

      # Development JWT secrets (loaded from .env file)
      # JWT_ACCESS_TOKEN_SECRET: loaded from .env
      # JWT_REFRESH_TOKEN_SECRET: loaded from .env

      # Session secrets (loaded from .env file)
      # SESSION_SECRET: loaded from .env
      # SESSION_STORE_SECRET: loaded from .env

      # Development email settings (optional)
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_SECURE: false
      # EMAIL_USER: your-email@gmail.com
      # EMAIL_PASSWORD: your-app-password

      # Development API keys (optional - add your own for testing)
      # CLOUDINARY_CLOUD_NAME: your-cloud-name
      # CLOUDINARY_KEY: your-api-key
      # CLOUDINARY_SECRET: your-api-secret
      # MAPBOX_TOKEN: your-mapbox-token
      # STRIPE_SECRET_KEY: your-stripe-secret-key
      # STRIPE_PUBLIC_KEY: your-stripe-public-key
      # OPENWEATHER_KEY: your-openweather-key
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules # Exclude node_modules from mount
      - /app/client/node_modules # Exclude client node_modules from mount
      - app_logs:/app/logs
    command: npm run dev # Use development command with hot reloading

  # Override MongoDB for development
  mongodb:
    environment:
      # Development database credentials
      MONGO_ROOT_USERNAME: admin
      MONGO_ROOT_PASSWORD: password
      MONGO_DATABASE: adventure-mate-dev
    ports:
      - '27017:27017' # Expose MongoDB port for local development tools

  # Override Redis for development
  redis:
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - '6379:6379' # Expose Redis port for local development tools

  # Add development tools (optional)
  mongo-express:
    profiles:
      - tools
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

  redis-commander:
    profiles:
      - tools
    environment:
      REDIS_HOSTS: local:redis:6379

volumes:
  # Development-specific volumes
  app_logs:
    driver: local
