// Mock for bson module
module.exports = {
  ObjectId: jest.fn().mockImplementation((id) => ({
    toString: () => id || '507f1f77bcf86cd799439011',
    toHexString: () => id || '507f1f77bcf86cd799439011',
  })),
  Binary: jest.fn(),
  Code: jest.fn(),
  DBRef: jest.fn(),
  Decimal128: jest.fn(),
  Double: jest.fn(),
  Int32: jest.fn(),
  Long: jest.fn(),
  MaxKey: jest.fn(),
  MinKey: jest.fn(),
  Timestamp: jest.fn(),
  UUID: jest.fn(),
  calculateObjectSize: jest.fn(),
  deserialize: jest.fn(),
  serialize: jest.fn(),
  BSONError: Error,
  BSONOffsetError: Error,
  BSONRegExp: RegExp,
  BSONRuntimeError: Error,
  BSONSymbol: Symbol,
  BSONType: Object,
  BSONValue: Object,
  BSONVersionError: Error,
};
